// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raoogxiqzinfxwjcfggm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhb29neGlxemluZnh3amNmZ2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5MzkzNjAsImV4cCI6MjEwNDUxNTM2MH0.EOQTVmUuNxVSYeUz6eqZ4wTRjXLaaj0lypxCO27PeG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});